title = "Woile"
author = "Santiago Fraire Willemoes"
base_url = "https://woile.eu"

[paths]
content = "content"
output = "public"
static = "static"
templates = "templates"

[nav]
nested = false  # Show child pages under sections
